spring.application.name=userservice
server.port=8181
spring.datasource.url= ${User-Service_DB-url}
spring.datasource.username=${user_name}
spring.datasource.password=${pass}

#spring.profiles.active=dev